/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject1;

import com.mycompany.mavenproject1.products.DialogAddCategory;
import com.mycompany.mavenproject1.products.PanelCategories;
import com.mycompany.mavenproject1.products.PanelProducts;
import com.mycompany.mavenproject1.sell.PanelSell;

/**
 *
 * @author geezylucas
 */
public class MainApplication extends javax.swing.JFrame {

    /**
     * Creates new form MainApplication
     */
    public MainApplication() {
        initComponents();
        PanelSell sell = new PanelSell();
        panelCentral.add(sell);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackgroud = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        sellMenu = new javax.swing.JMenu();
        sellMenuItem = new javax.swing.JMenuItem();
        repaymentMenuItem = new javax.swing.JMenuItem();
        productsMenu = new javax.swing.JMenu();
        categoriesMenuItem = new javax.swing.JMenuItem();
        addCategoryMenuItem = new javax.swing.JMenuItem();
        productsMenuItem = new javax.swing.JMenuItem();
        stockMenu = new javax.swing.JMenu();
        restockMenuItem = new javax.swing.JMenuItem();
        lowInventoryMenuItem = new javax.swing.JMenuItem();
        inventoryMenuItem = new javax.swing.JMenuItem();
        reportMovementsMenuItem = new javax.swing.JMenuItem();
        kardexProductMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelBackgroud.setLayout(new java.awt.BorderLayout());

        panelTitle.setBackground(new java.awt.Color(13, 44, 84));
        panelTitle.setForeground(new java.awt.Color(255, 255, 255));
        panelTitle.setPreferredSize(new java.awt.Dimension(1200, 70));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Nadeem", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBackgroud.add(panelTitle, java.awt.BorderLayout.PAGE_START);

        panelCentral.setLayout(new java.awt.CardLayout());
        panelBackgroud.add(panelCentral, java.awt.BorderLayout.CENTER);

        sellMenu.setText("Ventas");
        sellMenu.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N

        sellMenuItem.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N
        sellMenuItem.setText("Vender");
        sellMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellMenuItemActionPerformed(evt);
            }
        });
        sellMenu.add(sellMenuItem);

        repaymentMenuItem.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N
        repaymentMenuItem.setText("Devoluciones");
        repaymentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repaymentMenuItemActionPerformed(evt);
            }
        });
        sellMenu.add(repaymentMenuItem);

        menuBar.add(sellMenu);

        productsMenu.setText("Departamentos y Productos");
        productsMenu.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N

        categoriesMenuItem.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N
        categoriesMenuItem.setText("Departamentos");
        categoriesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesMenuItemActionPerformed(evt);
            }
        });
        productsMenu.add(categoriesMenuItem);

        addCategoryMenuItem.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N
        addCategoryMenuItem.setText("Crear Departamento");
        addCategoryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoryMenuItemActionPerformed(evt);
            }
        });
        productsMenu.add(addCategoryMenuItem);

        productsMenuItem.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N
        productsMenuItem.setText("Productos");
        productsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsMenuItemActionPerformed(evt);
            }
        });
        productsMenu.add(productsMenuItem);

        menuBar.add(productsMenu);

        stockMenu.setText("Inventarios");
        stockMenu.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N

        restockMenuItem.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N
        restockMenuItem.setText("Agregar inventario a producto");
        stockMenu.add(restockMenuItem);

        lowInventoryMenuItem.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N
        lowInventoryMenuItem.setText("Productos bajos de inventario");
        stockMenu.add(lowInventoryMenuItem);

        inventoryMenuItem.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N
        inventoryMenuItem.setText("Inventario de productos");
        stockMenu.add(inventoryMenuItem);

        reportMovementsMenuItem.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N
        reportMovementsMenuItem.setText("Reporte de movimientos");
        stockMenu.add(reportMovementsMenuItem);

        kardexProductMenuItem.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N
        kardexProductMenuItem.setText("Kardex de producto");
        stockMenu.add(kardexProductMenuItem);

        menuBar.add(stockMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");
        helpMenu.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N

        aboutMenuItem.setFont(new java.awt.Font("Nadeem", 0, 14)); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Acerca de");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackgroud, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sellMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellMenuItemActionPerformed
        // TODO add your handling code here:
        PanelSell sell = new PanelSell();
        panelCentral.removeAll();
        panelCentral.add(sell);
        panelCentral.validate();
        panelCentral.repaint();
    }//GEN-LAST:event_sellMenuItemActionPerformed

    private void repaymentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repaymentMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repaymentMenuItemActionPerformed

    private void categoriesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriesMenuItemActionPerformed
        // TODO add your handling code here:
        PanelCategories categories = new PanelCategories();
        panelCentral.removeAll();
        panelCentral.add(categories);
        panelCentral.validate();
        panelCentral.repaint();
    }//GEN-LAST:event_categoriesMenuItemActionPerformed

    private void addCategoryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategoryMenuItemActionPerformed
        // TODO add your handling code here:
        DialogAddCategory addCategory = new DialogAddCategory(this, true);
        addCategory.setLocationRelativeTo(null);
        addCategory.setVisible(true);
    }//GEN-LAST:event_addCategoryMenuItemActionPerformed

    private void productsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsMenuItemActionPerformed
        // TODO add your handling code here:
        PanelProducts products = new PanelProducts();
        panelCentral.removeAll();
        panelCentral.add(products);
        panelCentral.validate();
        panelCentral.repaint();
    }//GEN-LAST:event_productsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainApplication().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem addCategoryMenuItem;
    private javax.swing.JMenuItem categoriesMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem inventoryMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem kardexProductMenuItem;
    private javax.swing.JMenuItem lowInventoryMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panelBackgroud;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JMenu productsMenu;
    private javax.swing.JMenuItem productsMenuItem;
    private javax.swing.JMenuItem repaymentMenuItem;
    private javax.swing.JMenuItem reportMovementsMenuItem;
    private javax.swing.JMenuItem restockMenuItem;
    private javax.swing.JMenu sellMenu;
    private javax.swing.JMenuItem sellMenuItem;
    private javax.swing.JMenu stockMenu;
    // End of variables declaration//GEN-END:variables

}
