/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject1.sell;

import com.mycompany.mavenproject1.apiclient.ApiClient;
import com.mycompany.mavenproject1.apiclient.products.ProductsResponse;
import com.mycompany.mavenproject1.sqlite.SQLiteJDBC;
import com.mycompany.mavenproject1.utils.StyledButtonUI;
import com.mycompany.mavenproject1.utils.TextBubbleBorder;
import java.awt.Color;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

/**
 *
 * @author geezylucas
 */
public class PanelSell extends javax.swing.JPanel {

    /**
     * Creates new form PanelSell
     */
    public PanelSell() {
        initComponents();
        txtCodeProduct.requestFocusInWindow();
        tblProducts.getColumnModel().getColumn(0).setMinWidth(0);
        tblProducts.getColumnModel().getColumn(0).setMaxWidth(0);
        tblProducts.getColumnModel().getColumn(0).setWidth(0);
        tblProducts.setRowHeight(30);
        tblProducts.setShowGrid(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCodeProduct = new javax.swing.JLabel();
        txtCodeProduct = new javax.swing.JTextField();
        btnAddProduct = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnMoreOptions = new javax.swing.JButton();
        btnRemoveProduct = new javax.swing.JButton();
        btnSomeProducts = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCharge = new javax.swing.JButton();
        lblTotalMoney = new javax.swing.JLabel();
        lblTotalProducts = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnPendingSell = new javax.swing.JButton();
        btnPendingSells = new javax.swing.JButton();
        btnAssignClient = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Nadeem", 0, 18)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 110));

        lblCodeProduct.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblCodeProduct.setText("Código de producto:");

        txtCodeProduct.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        txtCodeProduct.setBorder(new TextBubbleBorder(Color.BLACK, 1, 3, 0));
        txtCodeProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeProductActionPerformed(evt);
            }
        });

        btnAddProduct.setBackground(new java.awt.Color(0, 166, 237));
        btnAddProduct.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setText("Agregar");
        btnAddProduct.setMaximumSize(new java.awt.Dimension(95, 40));
        btnAddProduct.setMinimumSize(new java.awt.Dimension(95, 40));
        btnAddProduct.setPreferredSize(new java.awt.Dimension(95, 40));
        btnAddProduct.setUI(new StyledButtonUI());
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("Venta Ticket #1");

        btnMoreOptions.setBackground(new java.awt.Color(0, 166, 237));
        btnMoreOptions.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnMoreOptions.setForeground(new java.awt.Color(255, 255, 255));
        btnMoreOptions.setText("Más opciones");
        btnMoreOptions.setMaximumSize(new java.awt.Dimension(117, 40));
        btnMoreOptions.setMinimumSize(new java.awt.Dimension(117, 40));
        btnMoreOptions.setPreferredSize(new java.awt.Dimension(117, 40));
        btnMoreOptions.setUI(new StyledButtonUI());

        btnRemoveProduct.setBackground(new java.awt.Color(246, 81, 29));
        btnRemoveProduct.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnRemoveProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveProduct.setText("Quitar producto");
        btnRemoveProduct.setMaximumSize(new java.awt.Dimension(117, 40));
        btnRemoveProduct.setMinimumSize(new java.awt.Dimension(117, 40));
        btnRemoveProduct.setPreferredSize(new java.awt.Dimension(117, 40));
        btnRemoveProduct.setUI(new StyledButtonUI());
        btnRemoveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveProductActionPerformed(evt);
            }
        });

        btnSomeProducts.setBackground(new java.awt.Color(0, 166, 237));
        btnSomeProducts.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnSomeProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnSomeProducts.setText("Varios");
        btnSomeProducts.setMaximumSize(new java.awt.Dimension(117, 40));
        btnSomeProducts.setMinimumSize(new java.awt.Dimension(117, 40));
        btnSomeProducts.setPreferredSize(new java.awt.Dimension(117, 40));
        btnSomeProducts.setUI(new StyledButtonUI());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCodeProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSomeProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(btnMoreOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodeProduct)
                    .addComponent(txtCodeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoreOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSomeProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 150));

        btnCharge.setBackground(new java.awt.Color(255, 180, 0));
        btnCharge.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btnCharge.setText("Cobrar");
        btnCharge.setUI(new StyledButtonUI());
        btnCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChargeActionPerformed(evt);
            }
        });

        lblTotalMoney.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lblTotalMoney.setText("$0.00");

        lblTotalProducts.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTotalProducts.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalProducts.setText("Total productos: 0");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Funciones adicionales:");

        btnPendingSell.setBackground(new java.awt.Color(127, 184, 0));
        btnPendingSell.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnPendingSell.setForeground(new java.awt.Color(255, 255, 255));
        btnPendingSell.setText("Venta pendiente");
        btnPendingSell.setUI(new StyledButtonUI());

        btnPendingSells.setBackground(new java.awt.Color(127, 184, 0));
        btnPendingSells.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnPendingSells.setForeground(new java.awt.Color(255, 255, 255));
        btnPendingSells.setText("Pendientes");
        btnPendingSells.setUI(new StyledButtonUI());

        btnAssignClient.setBackground(new java.awt.Color(127, 184, 0));
        btnAssignClient.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnAssignClient.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignClient.setText("Asignar a cliente");
        btnAssignClient.setMaximumSize(new java.awt.Dimension(165, 40));
        btnAssignClient.setMinimumSize(new java.awt.Dimension(165, 40));
        btnAssignClient.setPreferredSize(new java.awt.Dimension(165, 40));
        btnAssignClient.setUI(new StyledButtonUI());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAssignClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnPendingSell)
                .addGap(18, 18, 18)
                .addComponent(btnPendingSells)
                .addGap(212, 212, 212))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignClient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPendingSell, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPendingSells, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalProducts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCharge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTotalProducts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tblProducts.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Código de barras", "Producto", "Precio de venta", "Cantidad", "Importe", "Inventario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProducts);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChargeActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        addProduct();
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void txtCodeProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeProductActionPerformed
        // TODO add your handling code here:
        addProduct();
    }//GEN-LAST:event_txtCodeProductActionPerformed

    private void btnRemoveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveProductActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) this.tblProducts.getModel();
        int[] rows = this.tblProducts.getSelectedRows();
        for (int i = 0; i < rows.length; i++) {
            model.removeRow(rows[i] - i);
        }
        int totalProducts = 0;
        BigDecimal totalMoney = new BigDecimal(0);
        for (int i = 0; i < tblProducts.getRowCount(); i++) {//For each row
            totalProducts += (int) tblProducts.getValueAt(i, 4);
            String value = String.valueOf(tblProducts.getValueAt(i, 5));
            totalMoney = totalMoney.add(new BigDecimal(value));
        }//For loop outer   
        if (totalProducts == 0) {
            txtCodeProduct.requestFocusInWindow();
            lblTotalProducts.setText("Total productos: 0");
            lblTotalMoney.setText("$0.00");
        } else {
            lblTotalProducts.setText("Total productos: " + totalProducts);
            lblTotalMoney.setText("$" + totalMoney);
        }
    }//GEN-LAST:event_btnRemoveProductActionPerformed

    private void addProduct() {
        btnAddProduct.setBackground(Color.GRAY);
        btnAddProduct.setEnabled(false);
        if (!txtCodeProduct.getText().equals("")) {
            SQLiteJDBC sqlite = new SQLiteJDBC();
            String token = sqlite.getToken();
            Call<ProductsResponse> productResponseCall = ApiClient.getProductService().getProductByBarcodeWithQuantity(txtCodeProduct.getText(), "Bearer " + token);
            productResponseCall.enqueue(new Callback<ProductsResponse>() {
                @Override
                public void onResponse(Call<ProductsResponse> call, Response<ProductsResponse> response) {
                    if (response.isSuccessful()) {
                        ProductsResponse product = response.body();
                        if (product != null) {
                            DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
                            if (tblProducts.getRowCount() > 0) {
                                int row = -1;
                                for (int i = 0; i < tblProducts.getRowCount(); i++) {//For each row
                                    if (tblProducts.getModel().getValueAt(i, 0).equals(product.getId())) {//Search the model
                                        row = i;
                                        break;
                                    }
                                }//For loop outer   
                                if (row != -1) {
                                    int quantity = (int) tblProducts.getModel().getValueAt(row, 4) + 1;
                                    double stock = product.getStock() - quantity;
                                    if (stock >= 0) {
                                        tblProducts.getModel().setValueAt(quantity, row, 4);
                                        BigDecimal total = product.getPriceOut1().multiply(new BigDecimal(quantity));
                                        tblProducts.getModel().setValueAt(total, row, 5);
                                        tblProducts.getModel().setValueAt(stock, row, 6);
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Ya no quedan productos de " + product.getName() + "", "Producto", JOptionPane.ERROR_MESSAGE);
                                    }
                                } else {
                                    if (product.getStock() != null) {
                                        model.addRow(new Object[]{
                                            product.getId(),
                                            product.getBarcode(),
                                            product.getName(),
                                            product.getPriceOut1(),
                                            1,
                                            (product.getPriceOut1().multiply(new BigDecimal(1))),
                                            product.getStock() - 1
                                        });
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Ya no quedan productos de " + product.getName() + "", "Producto", JOptionPane.ERROR_MESSAGE);
                                    }
                                }
                            } else {
                                if (product.getStock() != null) {
                                    model.addRow(new Object[]{
                                        product.getId(),
                                        product.getBarcode(),
                                        product.getName(),
                                        product.getPriceOut1(),
                                        1,
                                        product.getPriceOut1().multiply(new BigDecimal(1)),
                                        product.getStock() - 1
                                    });
                                } else {
                                    JOptionPane.showMessageDialog(null, "Ya no quedan productos de " + product.getName() + "", "Producto", JOptionPane.ERROR_MESSAGE);
                                }
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "No existe el producto", "Producto", JOptionPane.ERROR_MESSAGE);
                    }
                    txtCodeProduct.requestFocusInWindow();
                    int totalProducts = 0;
                    BigDecimal totalMoney = new BigDecimal(0);
                    for (int i = 0; i < tblProducts.getRowCount(); i++) {//For each row
                        totalProducts += (int) tblProducts.getValueAt(i, 4);
                        String value = String.valueOf(tblProducts.getValueAt(i, 5));
                        totalMoney = totalMoney.add(new BigDecimal(value));
                    }//For loop outer   
                    lblTotalProducts.setText("Total productos: " + totalProducts);
                    lblTotalMoney.setText("$" + totalMoney);
                    btnAddProduct.setBackground(new java.awt.Color(0, 166, 237));
                    btnAddProduct.setEnabled(true);
                    txtCodeProduct.setText("");
                }

                @Override
                public void onFailure(Call<ProductsResponse> call, Throwable t) {
                    System.out.println(t.getLocalizedMessage());
                }
            }
            );
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnAssignClient;
    private javax.swing.JButton btnCharge;
    private javax.swing.JButton btnMoreOptions;
    private javax.swing.JButton btnPendingSell;
    private javax.swing.JButton btnPendingSells;
    private javax.swing.JButton btnRemoveProduct;
    private javax.swing.JButton btnSomeProducts;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodeProduct;
    private javax.swing.JLabel lblTotalMoney;
    private javax.swing.JLabel lblTotalProducts;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtCodeProduct;
    // End of variables declaration//GEN-END:variables
}
