/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject1.products;

import com.mycompany.mavenproject1.utils.TextBubbleBorder;
import java.awt.Color;

/**
 *
 * @author geezylucas
 */
public class PanelAddProduct extends javax.swing.JPanel {

    /**
     * Creates new form PanelAddProduct
     */
    public PanelAddProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupUnit = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBarcode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNameProduct = new javax.swing.JTextField();
        txtCostPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSalePrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSalePrice1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSalePrice2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDepartament = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMinimum = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtQuantityProduct = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rbUnit = new javax.swing.JRadioButton();
        rbPackage = new javax.swing.JRadioButton();
        rbBulk = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Nadeem", 1, 24)); // NOI18N
        jLabel1.setText("Agregar nuevo producto");

        jLabel2.setFont(new java.awt.Font("Nadeem", 0, 18)); // NOI18N
        jLabel2.setText("Código de barras:");

        txtBarcode.setFont(new java.awt.Font("Nadeem", 0, 17)); // NOI18N
        txtBarcode.setBorder(new TextBubbleBorder(Color.BLACK, 1, 3, 0));

        jLabel3.setFont(new java.awt.Font("Nadeem", 0, 18)); // NOI18N
        jLabel3.setText("Nombre producto:");

        txtNameProduct.setFont(new java.awt.Font("Nadeem", 0, 17)); // NOI18N
        txtNameProduct.setBorder(new TextBubbleBorder(Color.BLACK, 1, 3, 0));

        txtCostPrice.setFont(new java.awt.Font("Nadeem", 0, 17)); // NOI18N
        txtCostPrice.setBorder(new TextBubbleBorder(Color.BLACK, 1, 3, 0));

        jLabel4.setFont(new java.awt.Font("Nadeem", 0, 18)); // NOI18N
        jLabel4.setText("Precio costo:");

        txtSalePrice.setFont(new java.awt.Font("Nadeem", 0, 17)); // NOI18N
        txtSalePrice.setBorder(new TextBubbleBorder(Color.BLACK, 1, 3, 0));

        jLabel5.setFont(new java.awt.Font("Nadeem", 0, 18)); // NOI18N
        jLabel5.setText("Precio venta:");

        txtSalePrice1.setFont(new java.awt.Font("Nadeem", 0, 17)); // NOI18N
        txtSalePrice1.setBorder(new TextBubbleBorder(Color.BLACK, 1, 3, 0));

        jLabel6.setFont(new java.awt.Font("Nadeem", 0, 18)); // NOI18N
        jLabel6.setText("Precio venta dinámico:");

        txtSalePrice2.setFont(new java.awt.Font("Nadeem", 0, 17)); // NOI18N
        txtSalePrice2.setBorder(new TextBubbleBorder(Color.BLACK, 1, 3, 0));

        jLabel7.setFont(new java.awt.Font("Nadeem", 0, 18)); // NOI18N
        jLabel7.setText("Precio venta mayoreo:");

        jLabel8.setFont(new java.awt.Font("Nadeem", 0, 18)); // NOI18N
        jLabel8.setText("Departamento:");

        lblDepartament.setFont(new java.awt.Font("Nadeem", 0, 18)); // NOI18N
        lblDepartament.setText("Salchichonería");

        jLabel10.setFont(new java.awt.Font("Nadeem", 0, 18)); // NOI18N
        jLabel10.setText("Mínimo en inventario:");

        txtMinimum.setFont(new java.awt.Font("Nadeem", 0, 17)); // NOI18N
        txtMinimum.setBorder(new TextBubbleBorder(Color.BLACK, 1, 3, 0));

        jLabel11.setFont(new java.awt.Font("Nadeem", 0, 18)); // NOI18N
        jLabel11.setText("Cantidad de producto:");

        txtQuantityProduct.setFont(new java.awt.Font("Nadeem", 0, 17)); // NOI18N
        txtQuantityProduct.setBorder(new TextBubbleBorder(Color.BLACK, 1, 3, 0));

        jLabel12.setFont(new java.awt.Font("Nadeem", 0, 18)); // NOI18N
        jLabel12.setText("Nombre producto:");

        buttonGroupUnit.add(rbUnit);
        rbUnit.setFont(new java.awt.Font("Nadeem", 0, 18)); // NOI18N
        rbUnit.setText("Unidad");

        buttonGroupUnit.add(rbPackage);
        rbPackage.setFont(new java.awt.Font("Nadeem", 0, 18)); // NOI18N
        rbPackage.setText("Paquete");

        buttonGroupUnit.add(rbBulk);
        rbBulk.setFont(new java.awt.Font("Nadeem", 0, 18)); // NOI18N
        rbBulk.setText("Granel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBarcode)
                            .addComponent(txtNameProduct)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSalePrice2)
                            .addComponent(txtMinimum)
                            .addComponent(txtQuantityProduct)
                            .addComponent(lblDepartament, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbUnit)
                                .addGap(18, 18, 18)
                                .addComponent(rbPackage)
                                .addGap(18, 18, 18)
                                .addComponent(rbBulk))
                            .addComponent(txtCostPrice)
                            .addComponent(txtSalePrice)
                            .addComponent(txtSalePrice1))))
                .addContainerGap(687, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rbUnit)
                    .addComponent(rbPackage)
                    .addComponent(rbBulk))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCostPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalePrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalePrice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblDepartament))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMinimum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtQuantityProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblDepartament;
    private javax.swing.JRadioButton rbBulk;
    private javax.swing.JRadioButton rbPackage;
    private javax.swing.JRadioButton rbUnit;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtCostPrice;
    private javax.swing.JTextField txtMinimum;
    private javax.swing.JTextField txtNameProduct;
    private javax.swing.JTextField txtQuantityProduct;
    private javax.swing.JTextField txtSalePrice;
    private javax.swing.JTextField txtSalePrice1;
    private javax.swing.JTextField txtSalePrice2;
    // End of variables declaration//GEN-END:variables
}
